### ISSUE TITLE
HomeView > DetailView 이동 시 Darkmode 유지문제

### ISSUE THREAD

**Issue by JaewoongLee-swift** [DeveloperAcademy-POSTECH/MC2-Team6-BSNM#22]
HomeView에서 DetailView로 이동 시 다크모드가 유지되어서 글씨들, 버튼들이 모두 안보이는 현상이 있습니다. 해결이 필요해 보입니다.

**Comment by E-know** [comment]
라이트 모드만 지원하도록 수정했습니다.
