### ISSUE TITLE
DetailView 뒤로가기 버튼 미작동

### ISSUE THREAD

**Issue by JaewoongLee-swift** [DeveloperAcademy-POSTECH/MC2-Team6-BSNM#23]
DetailView의 뒤로가기 버튼이 작동하지 않습니다.

**Comment by E-know** [comment]
디테일 뷰에서 뒤로가기가 없고, 대신에 제스쳐가 대신하도록 수정했습니다.

**Comment by E-know** [comment]
대신에 디테일 뷰에서 사진 배경이 검정으로 나옵니다. 수정 부탁드립니다.
